;  ____       _   _   _
; / ___|  ___| |_| |_(_)_ __   __ _ ___
; \___ \ / _ \ __| __| | '_ \ / _` / __|
;  ___) |  __/ |_| |_| | | | | (_| \__ \
; |____/ \___|\__|\__|_|_| |_|\__, |___/
;                             |___/

[Variables]
font=Century Gothic
font2=Futurist Fixed-Width
style=NORMAL

color=255,255,255,180
highlight=#color#

language=en

;The time, date, and weather skins use this value to determine font sizes
;Don't change it unless you know what you're doing!
phi=0.618

;  ____  _         _
; / ___|| |_ _   _| | ___  ___
; \___ \| __| | | | |/ _ \/ __|
;  ___) | |_| |_| | |  __/\__ \
; |____/ \__|\__, |_|\___||___/
;            |___/

[allString]
AntiAlias=1
SolidColor=0,0,0,1
FontColor=#color#
StringStyle=#style#
FontFace=#font#

[subString]
FontFace=#font2#
FontSize=12
StringCase=UPPER
Padding=2,0,2,0
